project_id = "rscowwmoeycyxmfslhme"

[functions.rss-feed]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.sitemap-index]
verify_jwt = false

[functions.sitemap-categories]
verify_jwt = false

[functions.sitemap-topics]
verify_jwt = false

[functions.sitemap-blog]
verify_jwt = false